[features]
seeds = false
skip-lint = false
[programs.localnet]
my_dojo = "vrQ91QxPGytFvwMbnjj1DRwMnauD1EQYRVFuYDbhz3J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/boda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 3000000 tests/**/*.ts"
